server:
  ssl:
    key-store: ${KEY_STORE}
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
  http2:
    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
    generate-ddl: true

logging:
  level:
    grimuri: debug

cloud:
  aws:
    credentials:
      access-key: ${SQS_ACCESS_KEY}
      secret-key: ${SQS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sqs:
      endpoint: ${SQS_ENDPOINT}