spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/grimuri;NON_KEYWORDS=USER
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

logging:
  level:
    grimuri: debug

cloud:
  aws:
    credentials:
      access-key: ${SQS_ACCESS_KEY}
      secret-key: ${SQS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sqs:
      endpoint: ${SQS_ENDPOINT}